server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://rm-cn-nwy3k7qod0004xno.rwlb.rds.aliyuncs.com:3306/cloud_order?useSSL=false
    username: root
    password: 123456wW
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.example.cloud.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.example: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS